version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - alteepc-network

  db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=alteepc
      - POSTGRES_PASSWORD=alteepc_password
      - POSTGRES_DB=alteepc
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - alteepc-network
    restart: unless-stopped

networks:
  alteepc-network:
    driver: bridge

volumes:
  postgres-data:
